-- :name=cad_cli_produto
select a.seqproduto,
       a.seqfamilia,
       a.complemento,
       a.desccompleta,
       a.descreduzida,
       a.reffabricante,
       a.especificdetalhada,
       a.dtahorinclusao,
       a.usuarioinclusao,
       a.dtahoralteracao,
       a.usuarioalteracao,
       a.codprodfiscal,
       a.descgenerica
from map_produto a
 where 1=1;
 -- and rownum <=1000;
-- :name=cad_cli_familia
select a.seqfamilia,
       a.seqmarca,
       a.familia,
       a.pesavel,
       a.indisentopis,
       a.indiceformbaseipi,
       a.aliquotaipi,
       a.pmtdecimal,
       a.pmtmultiplicacao,
       a.dtahorinclusao,
       a.usuarioinclusao,
       a.dtahoralteracao,
       a.usuarioalteracao,
       a.codnbmsh,
       a.codnatrec,
       a.situacaonfpis,
       a.situacaonfcofins,
       a.situacaonfpissai,
       a.situacaonfcofinssai,
       a.ncmnovo,
       a.codcest
from map_familia a
 where 1=1;
 -- and rownum <=1000;
-- :name=cad_cli_famdivisao
select a.seqfamilia,
       a.nrodivisao,
       a.padraoembtransf,
       a.padraoembcompra,
       a.seqcomprador,
       a.nrotributacao,
       a.finalidadefamilia,
       a.formaabastecimento,
       a.dtahorinclusao,
       a.usuarioinclusao,
       a.dtahoralteracao,
       a.usuarioalteracao
from map_famdivisao a
 where 1=1;
 -- and rownum <=1000;
-- :name=cad_cli_tributacao
select a.nrotributacao,
       a.tributacao,
       a.descaplicacao,
       a.status,
       b.ufempresa,
       b.ufclientefornec,
       b.tiptributacao,
       b.nroregtributacao,
       b.pertributado,
       b.perisento,
       b.peroutro,
       b.peraliquota,
       b.peracrescst,
       b.peraliquotast,
       b.indapropriast,
       b.indpautaicms,
       b.pericmsantecipado,
       b.pericmspresumido,
       b.observacao,
       b.situacaonf,
       b.peraliqicmscalcpreco,
       b.indsomaipibaseicms,
       b.indreplicacao,
       b.indgeroureplicacao,
       b.peraliqfecp,
       b.perbasefecp,
       b.peracrescicmsantec,
       b.perdespicms,
       b.indsomaipibasest,
       b.peraliqicmsdif,
       b.indreduzbasest,
       b.dtaalteracao,
       b.usualteracao,
       b.aliquotaicmspmc,
       b.ressarcstvenda,
       b.peraliqfecop,
       b.percredcalcvpe,
       b.peraliquotavpe,
       b.peraliquotatare,
       b.pertributst,
       b.tipreducicmscalcst,
       b.tipcalcicmsselo,
       b.situacaonfpis,
       b.situacaonfcofins,
       b.codantecipst,
       b.diavenctost,
       b.indcalcstaliqcalcprc,
       b.tipocalcicmsfisci,
       b.indbaseicmslf,
       b.perpisdif,
       b.percofinsdif,
       b.peraliquotastcargagliq,
       b.indcalcstconfent,
       b.situacaonfipi,
       b.codobservacao,
       b.peracresicmsret,
       b.peraliqicmsret,
       b.perisentost,
       b.peroutrost,
       b.nrobaseexportacao,
       b.tipcalcfecp,
       b.indbasecempercreduzida,
       b.perbasepis,
       b.perbasecofins,
       b.situacaonfsimplesnac,
       b.calcicmsdescsuframa,
       b.calcicmsstdescsuframa,
       b.indredbaseicmsstsemdesp,
       b.seqconvprotocolognre,
       b.codnatrec,
       b.perpmc,
       b.indsomaipibaseantpres,
       b.indcalcicmsvpe,
       b.seqnatrec,
       b.inddeduzdescbasest,
       b.pertributadosuframaicms,
       b.peracrescicmsantecip,
       b.perredaliq,
       b.indbasecalcestornodifaliqrj,
       b.situacaonfdev,
       b.pericmsresolucao13,
       b.peraliqicmsdifer,
       b.indsomaipibaseicmsdifer,
       b.indsomafretebaseipi,
       b.permajoracaocofinsimport,
       b.indutilcustomesbase,
       b.percargatribmedia,
       b.percregimeatac,
       b.peracrescstresolucao13,
       b.perminicmsstret,
       b.pertributadocalc,
       b.perisentocalc,
       b.peroutrocalc,
       b.codobservacaocte,
       b.pertributadoantec,
       b.perisentoantec,
       b.peroutroantec,
       b.indaplicacrescstcargaliq,
       b.peraliqstcargaliqresolucao13,
       b.indcalcstembutprod,
       b.peraliqicmssolicit,
       b.pertributadoresol13,
       b.perisentoresol13,
       b.peroutroresol13,
       b.indcalcicmsdesonoutros,
       b.indcalcicmscredcusto,
       b.perredcargatribdi,
       b.permajoracaopisimport,
       b.peraliquotadestino,
       b.tipocalcicmspartilha,
       b.indtiposomaipiicmsantec,
       b.indutilredpresumst,
       b.tipocalcpresumido,
       b.indredicmscal,
       b.situacaonfcalc,
       b.peraliqicmsdeson,
       b.indcalcicmsantcusto,
       b.codobservacaodev,
       b.peraliqicmscalcresol13,
       b.seqformulafeef,
       b.basefcpst,
       b.peraliqfcpst,
       b.tipcalcfcpst,
       b.basefcpicms,
       b.peraliqfcpicms,
       b.tipcalcfcpicms,
       b.indcalcicmsefetivo,
       b.perredbcicmsefet
from map_tributacao   a,
     map_tributacaouf b
where 1=1
 and a.nrotributacao = b.nrotributacao;
-- and rownum <=1000;
-- :name=cad_cli_pessoa
select a.seqpessoa,
       a.versao,
       a.status,
       a.dtaativacao,
       a.nomerazao,
       a.fantasia,
       a.palavrachave,
       a.fisicajuridica,
       a.cidade,
       a.bairro,
       a.pais,
       a.uf,
       a.cep,
       a.logradouro,
       a.nrocgccpf,
       a.digcgccpf,
       a.inscricaorg,
       a.email,
       a.emailnfe,
       a.dtainclusao,
       a.usuinclusao,
       a.dtaalteracao,
       a.usualteracao
from ge_pessoa a
 where 1=1;
   --and rownum <=1000;
-- :name=cad_cli_fornecedor
select a.seqfornecedor,
       a.tipfornecedor,
       a.microempresa,
       a.statusgeral,
       a.dtaalteracao,
       a.usualteracao,
       b.nrodivisao,
       b.seqcomprador,
       b.nroregtributacao
from maf_fornecedor    a,
     maf_fornecdivisao b
where 1=1
 and a.seqfornecedor = b.seqfornecedor;
 --and rownum <=1000;
-- :name=cad_cli_prodcodigo
 select a.tipcodigo, 
        a.seqfamilia, 
        a.seqproduto, 
        a.qtdembalagem, 
        a.codacesso
from map_prodcodigo a
where 1=1;
 -- and rownum <= 1000;
